/**
 * WARNING: This file is automatically generated from:
 *  'src/scripting/api.h'
 * DO NOT CHANGE
 */

#include "scripting/wrapper.h"

#include <assert.h>
#include <limits>
#include <sstream>
#include <squirrel.h>

#include "scripting/api.h"

#include "squirrel/squirrel_error.hpp"

namespace UfoAPI {
namespace wrapper {

} // namespace wrapper
void register_ufo_wrapper(HSQUIRRELVM v)
{
  using namespace wrapper;

}

} // namespace UfoAPI

/* EOF */
