/**
 * WARNING: This file is automatically generated from:
 *  'src/scripting/api.h'
 * DO NOT CHANGE
 */
#ifndef HEADER_UFO_SCRIPTING_WRAPPER_H
#define HEADER_UFO_SCRIPTING_WRAPPER_H

#include <squirrel.h>

namespace UfoAPI {

void register_ufo_wrapper(HSQUIRRELVM v);


}

#endif

/* EOF */
