name: Windows C++ With MSVC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          # Install and bootstrap Vcpkg
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat

          # Install required libraries
          .\vcpkg.exe install curl:x64-windows libpng:x64-windows zlib:x64-windows glew:x64-windows glbinding:x64-windows glm:x64-windows

      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=D:/a/UFO-Cells/UFO-Cells/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_PREFIX_PATH=D:/a/UFO-Cells/UFO-Cells/vcpkg/installed/x64-windows -DCMAKE_BUILD_TYPE=Debug ..

      - name: Build
        working-directory: build
        run: cmake --build . --config Debug

      - name: Copy Libraries to Artifact
        run: |
          Copy-Item -Path $env:GITHUB_WORKSPACE\build\UFOCells.dll -Destination $env:GITHUB_WORKSPACE\UFOCells.dll
          Copy-Item -Path $env:GITHUB_WORKSPACE\build\UFOCells.lib -Destination $env:GITHUB_WORKSPACE\UFOCells.lib

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ufo-libraries-debug
          path: |
            ${{ github.workspace }}/UFOCells.dll
            ${{ github.workspace }}/UFOCells.lib
